### ISSUE TITLE
version conflict while using efficientnet code

### ISSUE THREAD

**Issue by shubhaminnani** [qubvel/efficientnet#45]
@qubvel what should be the version of tensorflow and keras so that there is no version conflict. This is not working in tensorflow-gpu==1.14 as well tensorflow-gpu==2.0.0-b1.
Thanks in advance.

**Comment by qubvel** [comment]
HI @shubhaminnani 
Code have been tested with 
1) tf 1.14 (cpu) + keras 2.2.4
2) tf.keras 1.14 (cpu)
3) tf 1.12 (gpu) + keras 2.2.4

What kind of error do you have? Could you provide a traceback?

**Comment by shubhaminnani** [comment]
Not in efficientnet but while training the code.

**Comment by shubhaminnani** [comment]
`img = preprocess_input(img)`


  File "/home/gpu3/anaconda3/envs/shubham/lib/python3.6/site-packages/efficientnet/preprocessing.py", line 56, in preprocess_input
    assert x.ndim in (3, 4)



`AttributeError: 'Tensor' object has no attribute 'ndim'`

**Comment by hasibzunair** [comment]
Check the variable type that is going in `preprocess_input`. It should be a numpy array of rank 3 or 4.
